# <center><font color=gray>Numpy</font>
***

<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold"><br>
Ndarrays

Les ndarrays sont des tableaux multidimensionnels efficaces dans le temps et dans l'espace au cœur de l'numpy.

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold">
Numpy arrays Rank 1:

In [4]:
import numpy as np

an_array = np.array([3, 33, 333])  # Create a rank 1 array

print(type(an_array))              # The type of an ndarray is: "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


**test du shape du tableau que nous venons de créer, il ne devrait avoir qu'une seule dimension (Rang 1)**

In [2]:
print(an_array.shape)

(3,)


In [3]:
# because this is a 1-rank array, we need only one index to accesss each element
print(an_array[0], an_array[1], an_array[2]) 

3 33 333


**Changer un élément du tableau**

In [58]:
an_array[0] =888

print(an_array)

[888  33 333]


In [59]:
an_array[1]=5
print(an_array)

[888   5 333]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold">
Numpy array Rank 1:</p>

Un **ndarray** de rang 2 est un tableau à deux dimensions. Notez le format ci-dessous de [[rangée] , [rangée] ]. Les tableaux à deux dimensions sont parfaits pour représenter des matrices qui sont souvent utiles en science des données.

In [5]:
another = np.array([[11,12,13],[21,22,23]])   # Create a rank 2 array

print(another)  # print the array

print("The shape is 2 rows, 3 columns: ", another.shape)  # rows x columns                   

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", another[0, 0], ", ",another[0, 1],", ", another[1, 0])

[[11 12 13]
 [21 22 23]]
Le shape est 2 lignes, 3 colonnes:  (2, 3)
Acceder aux elements [0,0], [0,1], et [1,0] du ndarray:  11 ,  12 ,  21


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold">
Il existe de plusieurs façons pour créer des numpy arrays:
</p>

Here we create a number of different size arrays with different shapes and different pre-filled values.  numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.




Je crée ici des tableaux de tailles différentes avec différentes formes et différentes valeurs.
Grace aux méthodes numpy intégrées on peu créer rapidement et des tableaux multidimensionnels.


In [6]:
import numpy as np

# create a 2x2 array of zeros
ex1 = np.zeros((2,2))      
print(ex1)                              

[[0. 0.]
 [0. 0.]]


In [7]:
# create a 2x2 array filled with 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)   

[[9. 9.]
 [9. 9.]]


In [8]:
# create a 2x2 matrix with the diagonal 1s and the others 0
ex3 = np.eye(2,2)
print(ex3)  

[[1. 0.]
 [0. 1.]]


In [9]:
# create an array of ones
ex4 = np.ones((1,2))
print(ex4)    

[[1. 1.]]


In [10]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array
print(ex4.shape)

# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)

1.0


In [11]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
print(ex5)    

[[0.0351622  0.87005846]
 [0.58990747 0.3813408 ]]


<p style="font-family: Arial; font-size:1.75em;color:purple; font-style:bold">
L'indexage de tableaux
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Slice indexing:
</p><br>
Tout comme l'indexation en slices avec des listes et des chaînes de caractères, on peut utiliser l'indexation par slices pour extraire les sous-régions des ndarrays.

In [12]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Utiliser le slicing pour obtenir un sous-tableau composé des 2 premières lignes x 2 colonnes.

In [15]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


Modifier un slice, modifie en fait le tableau sous-jacent.

In [16]:
print("Avant:", an_array[0, 1])
a_slice[0, 0] = 1000
print("Apres:", an_array[0, 1])    

Avant: 12
Apres: 1000


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Utiliser à la fois l'indexation en nombres entiers et l'indexation par slices
</p>

Nous pouvons utiliser des combinaisons d'indexation en nombres entiers et d'indexation en slices pour créer des matrices de formes différentes.

In [17]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [18]:
# Using both integer indexing & slicing generates an array of lower rank
row_rank1 = an_array[1, :]    # Rank 1 view 

print(row_rank1, row_rank1.shape)  # notice only a single []

[21 22 23 24] (4,)


In [20]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2, :]  # Rank 2 view 

print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[[21 22 23 24]] (1, 4)


In [73]:
#We can do the same thing for columns of an array:

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2


[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Array Indexing for changing elements:
</p>

Sometimes it's useful to use an array of indexes to access or change elements.

In [74]:
# Create a new array
an_array = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])

print('Original Array:')
print(an_array)

Original Array:
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [75]:
# Create an array of indices
col_indices = np.array([0, 1, 2, 0])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(4)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [76]:
# Examine the pairings of row_indices and col_indices.  These are the elements we'll change next.
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2
3 ,  0


In [78]:
# Select one element from each row
print('Values in the array at those indices: ',an_array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]


In [79]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011     12     13]
 [    21 100022     23]
 [    31     32 100033]
 [100041     42     43]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Boolean Indexing
<br><br></p>
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Array Indexing for changing elements:
</p>

In [80]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [81]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

Notice that the filter is a same size ndarray as an_array which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [82]:
# we can now select just those elements which meet that criteria
print(an_array[filter])

[21 22 31 32]


In [85]:
# For short, we could have just used the approach below without the need for the separate filter array.

an_array[(an_array > 15)]

array([21, 22, 31, 32])

What is particularly useful is that we can actually change elements in the array applying a similar logical filter.  Let's add 100 to all the even values.

In [87]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 212]
 [ 21 222]
 [ 31 232]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Datatypes and Array Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Datatypes:
</p>

In [93]:
ex1 = np.array([11, 12]) # Python assigns the  data type
print(ex1.dtype)

int32


In [94]:
ex2 = np.array([11.0, 12.0]) # Python assigns the  data type
print(ex2.dtype)

float64


In [95]:
ex3 = np.array([11, 21], dtype=np.int64) #You can also tell Python the  data type
print(ex3.dtype)

int64


In [96]:
# you can use this to force floats into integers (using floor function)
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [99]:
# you can use this to force integers into floats if you anticipate
# the values may change to floats later
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Arithmetic Array Operations:

</p>

In [100]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [101]:
# add
print(x + y)         # The plus sign works
print()
print(np.add(x, y))  # so does the numpy function "add"

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [102]:
# subtract
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [103]:
# multiply
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [104]:
# divide
print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [105]:
# square root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [106]:
# exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Statistical Methods, Sorting, and <br> <br> Set Operations:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Basic Statistical Operations:
</p>

In [107]:
# setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,5)
print(arr)

[[ -5.38400717   0.60636495  -3.46604036  -1.79378657   7.64440513]
 [ 17.58139686  -4.31934098  -7.92643411 -13.19952153   6.8156913 ]]


In [108]:
# compute the mean for all elements
print(arr.mean())

-0.34412724904769726


In [109]:
# compute the means by row
print(arr.mean(axis = 1))

[-0.47861281 -0.20964169]


In [110]:
# compute the means by column
print(arr.mean(axis = 0))

[ 6.09869484 -1.85648802 -5.69623724 -7.49665405  7.23004821]


In [111]:
# sum all the elements
print(arr.sum())

-3.4412724904769725


In [112]:
# compute the medians
print(np.median(arr, axis = 1))

[-1.79378657 -4.31934098]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sorting:
</p>


In [113]:
# create a 10 element array of randoms
unsorted = np.random.randn(10)

print(unsorted)

[ 0.13622648 -0.87996462  0.01183088  1.46843485 -1.92286609  0.95854821
  0.7408191  -0.69379759 -0.21398594 -0.18881032]


In [114]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-1.92286609 -0.87996462 -0.69379759 -0.21398594 -0.18881032  0.01183088
  0.13622648  0.7408191   0.95854821  1.46843485]

[ 0.13622648 -0.87996462  0.01183088  1.46843485 -1.92286609  0.95854821
  0.7408191  -0.69379759 -0.21398594 -0.18881032]


In [115]:
# inplace sorting
unsorted.sort() 

print(unsorted)

[-1.92286609 -0.87996462 -0.69379759 -0.21398594 -0.18881032  0.01183088
  0.13622648  0.7408191   0.95854821  1.46843485]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Finding Unique elements:
</p>

In [116]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Set Operations with np.array data type:
</p>

In [120]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [121]:
print( np.intersect1d(s1, s2) ) 

['bulb' 'chair']


In [122]:
print( np.union1d(s1, s2) )

['bulb' 'chair' 'desk' 'lamp']


In [123]:
print( np.setdiff1d(s1, s2) )# elements in s1 that are not in s2

['desk']


In [124]:
print( np.in1d(s1, s2) )#which element of s1 is also in s2

[False  True  True]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Broadcasting:
<br><br>
</p>

Introduction to broadcasting. <br>
For more details, please see: <br>
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [125]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [126]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [136]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [137]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [138]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [139]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Example from the slides:

In [140]:
# create our 3x4 matrix
arrA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [141]:
# create our 4x1 array
arrB = [0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [142]:
# add the two together using broadcasting
print(arrA + arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Speedtest: ndarrays vs lists
<br><br>
</p>

First setup paramaters for the speed test. We'll be testing time to sum elements in an ndarray versus a list.

In [143]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

In [144]:
# create the ndarray with values 0,1,2...,size-1
nd_array = arange(size)
print( type(nd_array) )

<class 'numpy.ndarray'>


In [145]:
# timer expects the operation as a parameter, 
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000494 seconds


In [146]:
# create the list with values 0,1,2...,size-1
a_list = list(range(size))
print (type(a_list) )

<class 'list'>


In [147]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list:  0.024363 seconds


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Read or Write to Disk:
<br><br>
</p>

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Binary Format:</p>

In [148]:
x = np.array([ 23.23, 24.24] )

In [149]:
np.save('an_array', x)

In [150]:
np.load('an_array.npy')

array([23.23, 24.24])

<p style="font-family: Arial; font-size:1.3em;color:#2462C0; font-style:bold"><br>

Text Format:</p>

In [154]:
np.savetxt('array.txt', X=x, delimiter=',')

In [157]:
np.loadtxt('array.txt', delimiter=',')

array([23.23, 24.24])

<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Additional Common ndarray Operations
<br><br></p>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Dot Product on Matrices and Inner Product on Vectors:

</p>

In [158]:
# determine the dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [160]:
# determine the inner product of two vectors
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print(a1d)
print(np.dot(a1d, b1d))

180
[9 9]
180


In [161]:
# dot produce on an array and vector
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))

[18 18]

[18 18]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Sum:
</p>

In [162]:
# sum elements in the array
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))          # add all members

66


In [163]:
print(np.sum(ex1, axis=0))  # columnwise sum

[32 34]


In [164]:
print(np.sum(ex1, axis=1))  # rowwise sum

[23 43]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Element-wise Functions: </p>

For example, let's compare two arrays values to get the maximum of each.

In [165]:
# random array
x = np.random.randn(8)
x

array([-1.01272204, -0.02532352,  1.35776018, -0.52152555, -0.64310207,
        0.13662599, -0.34872469, -0.9770932 ])

In [166]:
# another random array
y = np.random.randn(8)
y

array([ 0.80838645, -2.05990909, -1.07285894, -0.97096345,  0.97315085,
       -0.82561895,  0.21374771,  0.16846996])

In [167]:
# returns element wise maximum between two arrays

np.maximum(x, y)

array([ 0.80838645, -0.02532352,  1.35776018, -0.52152555,  0.97315085,
        0.13662599,  0.21374771,  0.16846996])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Reshaping array:
</p>

In [168]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [169]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Transpose:

</p>

In [170]:
# transpose
ex1 = np.array([[11,12],[21,22]])

ex1.T

array([[11, 21],
       [12, 22]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Indexing using where():</p>

In [171]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, False, True, False, True])

In [172]:
out = np.where(filter, x_1, y_1)
print(out)

[ 1 22  3 44  5]


In [173]:
mat = np.random.rand(5,5)
mat

array([[0.77427228, 0.34663957, 0.01967058, 0.5489815 , 0.26739162],
       [0.19293694, 0.18094455, 0.07058841, 0.67786703, 0.48541778],
       [0.77034923, 0.96783551, 0.93314148, 0.01845948, 0.11424922],
       [0.55516084, 0.24294238, 0.63365424, 0.28393594, 0.42341061],
       [0.11917337, 0.49153356, 0.69487594, 0.30352795, 0.22882648]])

In [174]:
np.where( mat > 0.5, 1000, -1)

array([[1000,   -1,   -1, 1000,   -1],
       [  -1,   -1,   -1, 1000,   -1],
       [1000, 1000, 1000,   -1,   -1],
       [1000,   -1, 1000,   -1,   -1],
       [  -1,   -1, 1000,   -1,   -1]])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

"any" or "all" conditionals:</p>

In [175]:
arr_bools = np.array([ True, False, True, True, False ])

In [176]:
arr_bools.any()

True

In [177]:
arr_bools.all()

False

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Random Number Generation:
</p>

In [185]:
Y = np.random.normal(size = (1,5))[0]
print(Y)

[-0.46520257 -1.02948779 -0.8382648   0.64269207  0.46693209]


In [186]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)

[29 43 10 32]


In [187]:
np.random.permutation(Z) #return a new ordering of elements in Z

array([32, 29, 10, 43])

In [201]:
np.random.uniform(size=4) #uniform distribution

array([0.69689828, 0.41614648, 0.19540872, 0.48402551])

In [199]:
np.random.normal(size=4) #normal distribution

array([-1.22201718, -1.42392198,  0.4794075 ,  1.39165954])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Merging data sets:
</p>

In [202]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[49 38]
 [32 33]]

[[40  2]
 [20 16]]


In [203]:
np.vstack((K,M))

array([[49, 38],
       [32, 33],
       [40,  2],
       [20, 16]])

In [204]:
np.hstack((K,M))

array([[49, 38, 40,  2],
       [32, 33, 20, 16]])

In [205]:
np.concatenate([K, M], axis = 0)

array([[49, 38],
       [32, 33],
       [40,  2],
       [20, 16]])

In [206]:
np.concatenate([K, M.T], axis = 1)

array([[49, 38, 40, 20],
       [32, 33,  2, 16]])